// ==UserScript==
// @name         BangumiCleaner (Delete Auto-generated Timeline Only)
// @namespace    https://github.com/Adachi-Git/BangumiCleaner
// @version      0.7
// @description  保留自己发的状态(.status)，删除其它自动生成时间线；自动翻页直到清空
// @author       Adachi
// @match        *://bgm.tv/user/*/timeline*
// @grant        none
// @license      MIT
// ==/UserScript==

(function () {
  'use strict';

  // 只在这个页面显示/运行（你当前的诉求）
  var TARGET_PATH = '/user/bool/timeline';
  if (location.pathname !== TARGET_PATH) return;

  var LS_RUNNING_KEY = 'bgm_cleaner_delete_auto_running';

  var BATCH_SIZE = 30;
  var BATCH_DELAY_MS = 800;
  var PAGE_DELAY_MS = 1200;

  function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

  function getHeaders() {
    return {
      'Accept': '*/*',
      'Accept-Encoding': 'gzip, deflate, br',
      'Accept-Language': 'zh-CN,zh;q=0.9',
      'Connection': 'keep-alive',
      'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
      'Cookie': document.cookie,
      'Host': window.location.hostname,
      'Referer': window.location.href,
      'Sec-Fetch-Dest': 'empty',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Site': 'same-origin',
      'User-Agent': navigator.userAgent,
      'X-Requested-With': 'XMLHttpRequest'
    };
  }

  // 自己发的稳定特征：包含 .status
  function isSelfStatusItem(tmlItem) {
    return !!tmlItem.querySelector('.status');
  }

  // 你要“保留 status，删除自动生成”：=> 删除条件是 “不是 status”
  function shouldDeleteItem(tmlItem) {
    return !isSelfStatusItem(tmlItem);
  }

  function getDeleteAnchorsOnThisPage_DeleteAutoOnly() {
    var items = Array.from(document.querySelectorAll('li.tml_item'));
    var dels = [];

    for (var item of items) {
      if (!shouldDeleteItem(item)) continue; // status 的跳过
      var del = item.querySelector('a.tml_del');
      if (del && del.href) dels.push(del);
    }
    return dels;
  }

  async function deleteBatch(anchors) {
    // 一批并发；失败继续后续
    var fetches = anchors.map(a =>
      fetch(a.href, {
        method: 'GET',
        headers: getHeaders(),
        credentials: 'same-origin'
      }).then(resp => {
        if (!resp.ok) throw new Error('HTTP ' + resp.status);
        return resp.text();
      })
    );

    try {
      await Promise.all(fetches);
      return { ok: anchors.length, fail: 0 };
    } catch (e) {
      console.error('[BangumiCleaner] 批量删除出现错误（继续执行）:', e);
      return { ok: 0, fail: anchors.length };
    }
  }

  async function deleteAutoGeneratedOnThisPage() {
    var targets = getDeleteAnchorsOnThisPage_DeleteAutoOnly();

    if (targets.length === 0) {
      console.log('[BangumiCleaner] 本页没有可删除的“自动生成(非status)”时间线。');
      return 0;
    }

    console.log('[BangumiCleaner] 本页待删除(非status)数量:', targets.length);

    var deleted = 0;
    for (var i = 0; i < targets.length; i += BATCH_SIZE) {
      var batch = targets.slice(i, i + BATCH_SIZE);
      var result = await deleteBatch(batch);
      deleted += result.ok;
      console.log('[BangumiCleaner] 本页进度: ' + Math.min(i + BATCH_SIZE, targets.length) + '/' + targets.length);
      await sleep(BATCH_DELAY_MS);
    }

    console.log('[BangumiCleaner] 本页删除完成(非status):', deleted);
    return deleted;
  }

  // 翻页：按你抓包的方式构造
  // https://bgm.tv/user/bool/timeline?type=all&page=2&ajax=1
  function buildNextPageUrlByQuery() {
    var url = new URL(location.href);

    // 维持 type=all（没有就补上）
    if (!url.searchParams.get('type')) url.searchParams.set('type', 'all');

    // 维持 ajax=1（没有就补上）
    if (url.searchParams.get('ajax') !== '1') url.searchParams.set('ajax', '1');

    var curPage = parseInt(url.searchParams.get('page') || '1', 10);
    if (!Number.isFinite(curPage) || curPage < 1) curPage = 1;

    url.searchParams.set('page', String(curPage + 1));
    return url.toString();
  }

  // 判断“是否还有下一页”
  // 没有可靠 DOM 的情况下：采用“试探式翻页”
  // 做法：请求下一页 HTML，如果里面没有任何 tml_item，就认为结束。
  async function hasAnyTimelineItemAt(url) {
    try {
      var resp = await fetch(url, {
        method: 'GET',
        headers: getHeaders(),
        credentials: 'same-origin'
      });
      if (!resp.ok) return false;
      var html = await resp.text();
      return html.includes('tml_item'); // 足够轻量的探测；你要更严谨我也可以改 DOMParser
    } catch (e) {
      console.error('[BangumiCleaner] 探测下一页失败:', e);
      return false;
    }
  }

  async function runOnceThenMaybeNext() {
    await deleteAutoGeneratedOnThisPage();
    await sleep(PAGE_DELAY_MS);

    var nextUrl = buildNextPageUrlByQuery();

    // 试探下一页是否还有内容；没有就结束，避免死循环翻页
    var ok = await hasAnyTimelineItemAt(nextUrl);
    if (!ok) {
      localStorage.removeItem(LS_RUNNING_KEY);
      alert('清理完成：下一页似乎没有时间线内容了。');
      return;
    }

    localStorage.setItem(LS_RUNNING_KEY, '1');
    location.href = nextUrl;
  }

  function mountButtonLeftOfSubmit() {
    var toolbar = document.querySelector('.tsukkmiToolbar');
    var submitWrap = document.querySelector('#submitBtnO');
    if (!toolbar || !submitWrap) {
      console.warn('[BangumiCleaner] 未找到 .tsukkmiToolbar 或 #submitBtnO，无法挂载按钮');
      return;
    }

    var wrap = document.createElement('div');
    wrap.className = 'rr';
    wrap.id = 'bgmCleanerDeleteAutoWrap';

    var btn = document.createElement('input');
    btn.type = 'button';
    btn.className = 'inputBtn';
    btn.value = '清空自动生成';
    btn.id = 'bgmCleanerDeleteAutoBtn';

    btn.addEventListener('click', function () {
      var ok = confirm('将保留自己发的状态(.status)，删除其它自动生成时间线，并自动翻页继续。\n确定开始？');
      if (!ok) return;

      localStorage.setItem(LS_RUNNING_KEY, '1');
      runOnceThenMaybeNext().catch(function (e) {
        console.error('[BangumiCleaner] 运行失败:', e);
        localStorage.removeItem(LS_RUNNING_KEY);
        alert('运行失败，详情见控制台。');
      });
    });

    wrap.appendChild(btn);
    toolbar.insertBefore(wrap, submitWrap);
  }

  mountButtonLeftOfSubmit();

  // 跨页自动继续
  if (localStorage.getItem(LS_RUNNING_KEY) === '1') {
    runOnceThenMaybeNext().catch(function (e) {
      console.error('[BangumiCleaner] 自动继续失败:', e);
      localStorage.removeItem(LS_RUNNING_KEY);
    });
  }
})();