// ==UserScript==
// @name         BangumiCleaner (Delete Auto-generated Timeline Only)
// @namespace    https://github.com/bgzo/playground
// @version      0.7
// @description  保留自己发的状态(.status)，删除其它自动生成时间线；自动翻页直到清空
// @author       bgzo
// @match        *://bangumi.tv/user/*/timeline
// @match        *://bgm.tv/user/*/timeline
// @match        *://chii.in/user/*/timeline
// @grant        none
// @license      MIT
// ==/UserScript==

(function () {
  'use strict';

  // 只在这个页面显示/运行（你当前的诉求）
  var TARGET_PATH = '/user/bool/timeline';
  if (location.pathname !== TARGET_PATH) return;

  var LS_RUNNING_KEY = 'bgm_cleaner_delete_auto_running';
  var LS_PAGE_KEY = 'bgm_cleaner_delete_auto_page';

  var BATCH_SIZE = 30;
  var BATCH_DELAY_MS = 800;
  var PAGE_DELAY_MS = 1200;

  function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

  function getHeaders() {
    return {
      'Accept': '*/*',
      'Accept-Encoding': 'gzip, deflate, br',
      'Accept-Language': 'zh-CN,zh;q=0.9',
      'Connection': 'keep-alive',
      'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
      'Cookie': document.cookie,
      'Host': window.location.hostname,
      'Referer': window.location.href,
      'Sec-Fetch-Dest': 'empty',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Site': 'same-origin',
      'User-Agent': navigator.userAgent,
      'X-Requested-With': 'XMLHttpRequest'
    };
  }

  function getCurrentPage() {
    var storedPage = parseInt(localStorage.getItem(LS_PAGE_KEY) || '', 10);
    if (Number.isFinite(storedPage) && storedPage > 0) return storedPage;

    var page = parseInt(new URL(location.href).searchParams.get('page') || '1', 10);
    return Number.isFinite(page) && page > 0 ? page : 1;
  }

  // 自己发的稳定特征：包含 .status
  function isSelfStatusItem(tmlItem) {
    return !!tmlItem.querySelector('.status');
  }

  // 你要“保留 status，删除自动生成”：=> 删除条件是 “不是 status”
  function shouldDeleteItem(tmlItem) {
    return !isSelfStatusItem(tmlItem);
  }

  function getDeleteAnchorsOnThisPage_DeleteAutoOnly() {
    var items = Array.from(document.querySelectorAll('li.tml_item'));
    var dels = [];

    for (var item of items) {
      if (!shouldDeleteItem(item)) continue; // status 的跳过
      var del = item.querySelector('a.tml_del');
      if (del && del.href) dels.push(del);
    }
    return dels;
  }

  async function deleteBatch(anchors) {
    // 一批并发；失败继续后续
    var fetches = anchors.map(a =>
      fetch(a.href, {
        method: 'GET',
        headers: getHeaders(),
        credentials: 'same-origin'
      }).then(resp => {
        if (!resp.ok) throw new Error('HTTP ' + resp.status);
        return resp.text();
      })
    );

    try {
      await Promise.all(fetches);
      return { ok: anchors.length, fail: 0 };
    } catch (e) {
      console.error('[BangumiCleaner] 批量删除出现错误（继续执行）:', e);
      return { ok: 0, fail: anchors.length };
    }
  }

  async function deleteAutoGeneratedOnThisPage() {
    var targets = getDeleteAnchorsOnThisPage_DeleteAutoOnly();

    if (targets.length === 0) {
      console.log('[BangumiCleaner] 本页没有可删除的“自动生成(非status)”时间线。');
      return 0;
    }

    console.log('[BangumiCleaner] 本页待删除(非status)数量:', targets.length);

    var deleted = 0;
    for (var i = 0; i < targets.length; i += BATCH_SIZE) {
      var batch = targets.slice(i, i + BATCH_SIZE);
      var result = await deleteBatch(batch);
      deleted += result.ok;
      console.log('[BangumiCleaner] 本页进度: ' + Math.min(i + BATCH_SIZE, targets.length) + '/' + targets.length);
      await sleep(BATCH_DELAY_MS);
    }

    console.log('[BangumiCleaner] 本页删除完成(非status):', deleted);
    return deleted;
  }

  // 翻页：按你抓包的方式构造
  // https://bgm.tv/user/bool/timeline?type=all&page=2&ajax=1
  function buildPageUrl(page) {
    var url = new URL(location.href);

    // 维持 type=all（没有就补上）
    if (!url.searchParams.get('type')) url.searchParams.set('type', 'all');

    // 维持 ajax=1（没有就补上）
    if (url.searchParams.get('ajax') !== '1') url.searchParams.set('ajax', '1');

    url.searchParams.set('page', String(page));
    return url.toString();
  }

  function buildVisiblePageUrl(page) {
    var url = new URL(location.href);
    if (!url.searchParams.get('type')) url.searchParams.set('type', 'all');
    url.searchParams.delete('ajax');
    url.searchParams.set('page', String(page));
    return url.toString();
  }

  function parseTimelineContainerFromHtml(html) {
    var wrapper = document.createElement('div');
    wrapper.innerHTML = html;

    var firstItem = wrapper.querySelector('li.tml_item');
    if (!firstItem || !firstItem.parentElement) return null;

    return firstItem.parentElement;
  }

  function getCurrentTimelineContainer() {
    var firstItem = document.querySelector('li.tml_item');
    return firstItem ? firstItem.parentElement : null;
  }

  async function fetchTimelinePageHtml(url) {
    try {
      var resp = await fetch(url, {
        method: 'GET',
        headers: getHeaders(),
        credentials: 'same-origin'
      });
      if (!resp.ok) return null;
      return await resp.text();
    } catch (e) {
      console.error('[BangumiCleaner] 拉取时间线页失败:', e);
      return null;
    }
  }

  function replaceTimelineWithHtml(html) {
    var currentContainer = getCurrentTimelineContainer();
    var nextContainer = parseTimelineContainerFromHtml(html);

    if (!currentContainer || !nextContainer) return false;

    currentContainer.innerHTML = nextContainer.innerHTML;
    return true;
  }

  async function runCleanupLoop() {
    var currentPage = getCurrentPage();

    while (true) {
      console.log('[BangumiCleaner] 开始处理第 ' + currentPage + ' 页');
      await deleteAutoGeneratedOnThisPage();
      await sleep(PAGE_DELAY_MS);

      var nextPage = currentPage + 1;
      var nextHtml = await fetchTimelinePageHtml(buildPageUrl(nextPage));
      if (!nextHtml || !nextHtml.includes('tml_item')) {
        localStorage.removeItem(LS_RUNNING_KEY);
        localStorage.removeItem(LS_PAGE_KEY);
        history.replaceState(null, '', buildVisiblePageUrl(currentPage));
        alert('清理完成：后续页似乎没有时间线内容了。');
        return;
      }

      if (!replaceTimelineWithHtml(nextHtml)) {
        throw new Error('无法替换下一页时间线 DOM');
      }

      currentPage = nextPage;
      localStorage.setItem(LS_PAGE_KEY, String(currentPage));
      history.replaceState(null, '', buildVisiblePageUrl(currentPage));
      await sleep(PAGE_DELAY_MS);
    }
  }

  function mountButtonLeftOfSubmit() {
    var toolbar = document.querySelector('.tsukkmiToolbar');
    var submitWrap = document.querySelector('#submitBtnO');
    if (!toolbar || !submitWrap) {
      console.warn('[BangumiCleaner] 未找到 .tsukkmiToolbar 或 #submitBtnO，无法挂载按钮');
      return;
    }

    var wrap = document.createElement('div');
    wrap.className = 'rr';
    wrap.id = 'bgmCleanerDeleteAutoWrap';

    var btn = document.createElement('input');
    btn.type = 'button';
    btn.className = 'inputBtn';
    btn.value = '清空自动生成';
    btn.id = 'bgmCleanerDeleteAutoBtn';
    btn.style.background = '#d0d0d0';
    btn.style.borderColor = '#b5b5b5';
    btn.style.color = '#333';

    btn.addEventListener('click', function () {
      var ok = confirm('将保留自己发的状态(.status)，删除其它自动生成时间线，并自动翻页继续。\n确定开始？');
      if (!ok) return;

      localStorage.setItem(LS_PAGE_KEY, String(getCurrentPage()));
      localStorage.setItem(LS_RUNNING_KEY, '1');
      runCleanupLoop().catch(function (e) {
        console.error('[BangumiCleaner] 运行失败:', e);
        localStorage.removeItem(LS_RUNNING_KEY);
        localStorage.removeItem(LS_PAGE_KEY);
        alert('运行失败，详情见控制台。');
      });
    });

    wrap.appendChild(btn);
    submitWrap.parentNode.insertBefore(wrap, submitWrap.nextSibling);
  }

  mountButtonLeftOfSubmit();

  // 跨页自动继续
  if (localStorage.getItem(LS_RUNNING_KEY) === '1') {
    runCleanupLoop().catch(function (e) {
      console.error('[BangumiCleaner] 自动继续失败:', e);
      localStorage.removeItem(LS_RUNNING_KEY);
      localStorage.removeItem(LS_PAGE_KEY);
    });
  }
})();